#server配置信息
server:
  port: 8002
  servlet:
    context-path: /notes

logging:
  name: notes
  path: /data/log/notes


spring:
  application:
    name: spring-boot-notes
  # 环境 normal|test
  profiles: test
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    test-on-borrow: true
    password: Credit2020
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 5000
        min-idle: 10



#redis
redis:
  # Redis数据库索引（默认为0）
  database: 0
  # Redis服务器地址
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  # Redis服务器连接密码（默认为空）
  password: Credit2020
  # 连接超时时间（毫秒）
  timeout: 5000
  pool:
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: -1
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池中的最小空闲连接
    min-idle: 0
    # 最大链接数
    max-total: 500