#server配置信息
server:
  port: 8002
  servlet:
    context-path: /notes

logging:
  name: notes
  path: /data/log/notes


spring:
  application:
    name: spring-boot-notes
  # 环境 normal|test
  profiles: test
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    test-on-borrow: true
    password:
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 5000
        min-idle: 10
  redis2:
    cluster:
      nodes: 192.168.200.87:7001,192.168.200.87:7002,192.168.200.87:7003
    timeout: 10000
    test-on-borrow: true
    password:
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 5000
        min-idle: 10

