spring:allatori
  profiles:
    active: dev



app:
  oss:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAIuvJKeN9XnIAU
    accessKeySecret: Z9S8l2Zjr1qfkjS41XBcuUWmGYLFLP
    publicBucketName: zjjtv-public
    privateBucketName: zjjtv-private